Repository woowa-turkey/miniprojects-2019, pull requests merged in 2019-09, with the labels that each got.

#98 메신저 기능 구현했습니다~
  build.gradle
  src/main/java/com/wootecobook/turkey/commons/interceptor/HttpHandshakeInterceptor.java
  src/main/java/com/wootecobook/turkey/config/WebSocketConfig.java
  src/main/java/com/wootecobook/turkey/messenger/controller/MessengerApiController.java
  src/main/java/com/wootecobook/turkey/messenger/controller/MessengerApiControllerAdvice.java
  src/main/java/com/wootecobook/turkey/messenger/controller/MessengerController.java
  src/main/java/com/wootecobook/turkey/messenger/controller/MessengerControllerAdvice.java
  src/main/java/com/wootecobook/turkey/messenger/controller/WebSocketMessengerController.java
  src/main/java/com/wootecobook/turkey/messenger/domain/Message.java
  src/main/java/com/wootecobook/turkey/messenger/domain/MessageRepository.java
  src/main/java/com/wootecobook/turkey/messenger/domain/Messenger.java
  src/main/java/com/wootecobook/turkey/messenger/domain/MessengerRepository.java
  src/main/java/com/wootecobook/turkey/messenger/domain/MessengerRoom.java
  src/main/java/com/wootecobook/turkey/messenger/domain/MessengerRoomRepository.java
  src/main/java/com/wootecobook/turkey/messenger/domain/exception/InvalidMessengerRoomException.java
  src/main/java/com/wootecobook/turkey/messenger/service/MessageService.java
  src/main/java/com/wootecobook/turkey/messenger/service/MessengerRoomService.java
  src/main/java/com/wootecobook/turkey/messenger/service/MessengerService.java
  src/main/java/com/wootecobook/turkey/messenger/service/dto/MessageRequest.java
  src/main/java/com/wootecobook/turkey/messenger/service/dto/MessageResponse.java
  src/main/java/com/wootecobook/turkey/messenger/service/dto/MessengerRequest.java
  src/main/java/com/wootecobook/turkey/messenger/service/dto/MessengerRoomResponse.java
  src/main/java/com/wootecobook/turkey/messenger/service/exception/AccessDeniedException.java
  src/main/java/com/wootecobook/turkey/messenger/service/strategy/JoinStrategy.java
  src/main/java/com/wootecobook/turkey/messenger/service/strategy/MessengerRoomCodeStrategy.java
  src/main/java/com/wootecobook/turkey/messenger/service/strategy/MessengerRoomCodeStrategyConfig.java
  src/main/resources/static/css/messenger.css
  src/main/resources/static/js/friendbar/load.js
  src/main/resources/static/js/friendbar/template.js
  src/main/resources/static/js/messenger/messenger.js
  src/main/resources/static/js/messenger/template.js
  src/main/resources/templates/messenger.html
  src/test/java/com/wootecobook/turkey/BaseControllerTests.java
  src/test/java/com/wootecobook/turkey/messenger/controller/MessengerApiControllerTest.java
  src/test/java/com/wootecobook/turkey/messenger/controller/MessengerControllerTest.java
  src/test/java/com/wootecobook/turkey/messenger/controller/WebSocketMessengerControllerTest.java
  src/test/java/com/wootecobook/turkey/messenger/service/MessageServiceTest.java
  src/test/java/com/wootecobook/turkey/messenger/service/MessengerRoomServiceTest.java
  src/test/java/com/wootecobook/turkey/messenger/service/MessengerServiceTest.java
Labels: enhancement

#120 친구 삭제시 의도하지 않은 에러메시지 수정
  src/main/java/com/wootecobook/turkey/friend/service/dto/FriendResponse.java
  src/main/java/com/wootecobook/turkey/user/domain/User.java
  src/main/java/com/wootecobook/turkey/user/service/UserService.java
  src/main/resources/static/js/friendask/load.js
  src/main/resources/static/js/friendbar/load.js
  src/main/resources/static/js/friendbar/template.js
Labels: bug

#121 REST docs 적용 완료
  build.gradle
  src/docs/asciidoc/api-guide.adoc
  src/main/java/com/wootecobook/turkey/config/WebConfig.java
  src/test/java/com/wootecobook/turkey/BaseControllerTests.java
  src/test/java/com/wootecobook/turkey/comment/controller/CommentApiControllerTests.java
  src/test/java/com/wootecobook/turkey/commons/aws/S3ConnectorTest.java
  src/test/java/com/wootecobook/turkey/file/service/UploadFileServiceTest.java
  src/test/java/com/wootecobook/turkey/friend/controller/FriendApiControllerTests.java
  src/test/java/com/wootecobook/turkey/login/controller/LoginApiControllerTests.java
  src/test/java/com/wootecobook/turkey/post/controller/PostApiControllerTests.java
  src/test/java/com/wootecobook/turkey/search/controller/SearchControllerTests.java
  src/test/java/com/wootecobook/turkey/user/controller/IntroductionApiControllerTests.java
  src/test/java/com/wootecobook/turkey/user/controller/UserApiControllerTests.java
  src/test/java/com/wootecobook/turkey/user/controller/UserControllerTests.java
Labels: documentation

#123 검색시 이상한 글씨 넣으면 에러페이지로 가지는 문제 해결
  src/main/java/com/wootecobook/turkey/search/controller/SearchController.java
  src/main/java/com/wootecobook/turkey/user/controller/UserApiController.java
  src/main/resources/static/js/search/searchResult.js
  src/main/resources/static/js/search/searchbox.js
  src/test/java/com/wootecobook/turkey/user/controller/UserApiControllerTests.java
Labels: bug

#125 mypage에서 가끔 글이 안써지는 문제 해결
  src/main/resources/static/js/mypage/mypage.js
Labels: bug

#126 배포서버에서 게시글 작성시간 잘못 나오는 것 수정
  deploy.sh
  src/main/resources/static/js/post/template.js
Labels: bug

#127 / 포함하면 검색 안되는 문제
  src/main/resources/static/js/search/searchbox.js
Labels: bug

#129 good Service 객체 @Transactional 피드백 반영
  src/main/java/com/wootecobook/turkey/good/service/CommentGoodService.java
  src/main/java/com/wootecobook/turkey/good/service/GoodService.java
  src/main/java/com/wootecobook/turkey/good/service/PostGoodService.java
  src/main/java/com/wootecobook/turkey/post/service/PostService.java
Labels: refactor

#132 함께한 친구 태그 기능 추가
  src/main/java/com/wootecobook/turkey/friend/service/FriendService.java
  src/main/java/com/wootecobook/turkey/post/controller/PostApiControllerAdvice.java
  src/main/java/com/wootecobook/turkey/post/domain/Post.java
  src/main/java/com/wootecobook/turkey/post/service/PostService.java
  src/main/java/com/wootecobook/turkey/post/service/dto/PostRequest.java
  src/main/java/com/wootecobook/turkey/post/service/dto/PostResponse.java
  src/main/java/com/wootecobook/turkey/post/service/exception/NotFriendException.java
  src/main/resources/static/css/friendtag.css
  src/main/resources/static/images/default/icons5.png
  src/main/resources/static/js/mypage/template-writeform.js
  src/main/resources/static/js/post/friend-tag.js
  src/main/resources/static/js/post/post.js
  src/main/resources/static/js/post/template.js
  src/main/resources/templates/fragments/friend-tag-modal.html
  src/main/resources/templates/fragments/write-post.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layouts/main.html
  src/main/resources/templates/mypage.html
  src/test/java/com/wootecobook/turkey/BaseControllerTests.java
  src/test/java/com/wootecobook/turkey/messenger/service/MessengerServiceTest.java
  src/test/java/com/wootecobook/turkey/post/controller/PostApiControllerTests.java
  src/test/java/com/wootecobook/turkey/post/service/PostServiceTest.java
Labels: enhancement
