Repository woowa-turkey/miniprojects-2019, pull requests merged in 2019-08, with the labels that each got.

#13 회원 도메인 개발
  build.gradle
  src/main/java/com/wootecobook/turkey/user/controller/UserController.java
  src/main/java/com/wootecobook/turkey/user/controller/api/ErrorMessage.java
  src/main/java/com/wootecobook/turkey/user/controller/api/UserApiController.java
  src/main/java/com/wootecobook/turkey/user/controller/api/UserApiControllerExceptionAdvice.java
  src/main/java/com/wootecobook/turkey/user/controller/web/UserController.java
  src/main/java/com/wootecobook/turkey/user/domain/User.java
  src/main/java/com/wootecobook/turkey/user/domain/UserRepository.java
  src/main/java/com/wootecobook/turkey/user/domain/UserValidator.java
  src/main/java/com/wootecobook/turkey/user/service/UserService.java
  src/main/java/com/wootecobook/turkey/user/service/dto/UserRequest.java
  src/main/java/com/wootecobook/turkey/user/service/dto/UserResponse.java
  src/main/java/com/wootecobook/turkey/user/service/exception/NotFoundUserException.java
  src/main/java/com/wootecobook/turkey/user/service/exception/SignUpException.java
  src/main/java/com/wootecobook/turkey/user/service/exception/UserDeleteException.java
  src/main/resources/templates/signup.html
  src/test/java/com/wootecobook/turkey/user/controller/BaseControllerTests.java
  src/test/java/com/wootecobook/turkey/user/controller/api/UserApiControllerTests.java
  src/test/java/com/wootecobook/turkey/user/controller/web/UserControllerTest.java
  src/test/java/com/wootecobook/turkey/user/service/UserServiceTest.java
Labels: enhancement

#21 로그인, 로그아웃 개발
  src/main/java/com/wootecobook/turkey/commons/exception/NotLoginException.java
  src/main/java/com/wootecobook/turkey/commons/resolver/UserSession.java
  src/main/java/com/wootecobook/turkey/commons/resolver/UserSessionArgumentResolver.java
  src/main/java/com/wootecobook/turkey/config/ResolverConfig.java
  src/main/java/com/wootecobook/turkey/login/controller/api/LoginApiController.java
  src/main/java/com/wootecobook/turkey/login/controller/api/LoginApiControllerAdvice.java
  src/main/java/com/wootecobook/turkey/login/service/LoginService.java
  src/main/java/com/wootecobook/turkey/login/service/dto/LoginRequest.java
  src/main/java/com/wootecobook/turkey/login/service/exception/LoginFailException.java
  src/main/java/com/wootecobook/turkey/post/domain/Post.java
  src/main/java/com/wootecobook/turkey/user/controller/api/UserApiController.java
  src/main/java/com/wootecobook/turkey/user/controller/api/UserApiControllerAdvice.java
  src/main/java/com/wootecobook/turkey/user/controller/api/UserApiControllerExceptionAdvice.java
  src/main/java/com/wootecobook/turkey/user/domain/User.java
  src/main/java/com/wootecobook/turkey/user/domain/UserRepository.java
  src/main/java/com/wootecobook/turkey/user/service/UserService.java
  src/main/java/com/wootecobook/turkey/user/service/exception/UserMismatchException.java
  src/test/java/com/wootecobook/turkey/login/controller/api/LoginApiControllerTests.java
  src/test/java/com/wootecobook/turkey/login/service/LoginServiceTest.java
  src/test/java/com/wootecobook/turkey/user/controller/BaseControllerTests.java
  src/test/java/com/wootecobook/turkey/user/controller/api/UserApiControllerTests.java
  src/test/java/com/wootecobook/turkey/user/domain/UserTest.java
  src/test/java/com/wootecobook/turkey/user/service/UserServiceTest.java
Labels: enhancement

#14 [게시글 도메인 개발] 철시, 올라프 미션 제출합니다.
  src/main/java/com/wootecobook/turkey/TurkeyApplication.java
  src/main/java/com/wootecobook/turkey/commons/ErrorMessage.java
  src/main/java/com/wootecobook/turkey/commons/aop/LoggingAspect.java
  src/main/java/com/wootecobook/turkey/post/PostControllerAdvice.java
  src/main/java/com/wootecobook/turkey/post/controller/PostApiController.java
  src/main/java/com/wootecobook/turkey/post/controller/PostController.java
  src/main/java/com/wootecobook/turkey/post/controller/exception/PostBadRequestException.java
  src/main/java/com/wootecobook/turkey/post/domain/Contents.java
  src/main/java/com/wootecobook/turkey/post/domain/Post.java
  src/main/java/com/wootecobook/turkey/post/domain/PostRepository.java
  src/main/java/com/wootecobook/turkey/post/domain/exception/InvalidContentException.java
  src/main/java/com/wootecobook/turkey/post/domain/exception/InvalidPostException.java
  src/main/java/com/wootecobook/turkey/post/domain/exception/PostUpdateFailException.java
  src/main/java/com/wootecobook/turkey/post/service/PostService.java
  src/main/java/com/wootecobook/turkey/post/service/dto/PostRequest.java
  src/main/java/com/wootecobook/turkey/post/service/dto/PostResponse.java
  src/main/java/com/wootecobook/turkey/post/service/exception/NotFoundPostException.java
  src/main/resources/static/css/edit.css
  src/main/resources/static/css/index.css
  src/main/resources/static/js/post/api.js
  src/main/resources/static/js/post/post.js
  src/main/resources/static/js/post/template.js
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/fragments/write-post.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layouts/main.html
  src/test/java/com/wootecobook/turkey/post/controller/PostApiControllerTest.java
  src/test/java/com/wootecobook/turkey/post/domain/ContentsTest.java
  src/test/java/com/wootecobook/turkey/post/domain/PostTest.java
  src/test/java/com/wootecobook/turkey/post/service/PostServiceTest.java
Labels: enhancement

#22 테스트 깨지는 문제 해결했습니다
  src/main/java/com/wootecobook/turkey/TurkeyApplication.java
  src/main/java/com/wootecobook/turkey/commons/aop/LoggingAspect.java
  src/main/java/com/wootecobook/turkey/config/ResolverConfig.java
  src/test/java/com/wootecobook/turkey/post/controller/PostApiControllerTest.java
Labels: bug

#23 Post에 유저 매핑 기능 완료했습니다.
  src/main/java/com/wootecobook/turkey/post/controller/PostApiController.java
  src/main/java/com/wootecobook/turkey/post/domain/Post.java
  src/main/java/com/wootecobook/turkey/post/service/PostService.java
  src/main/java/com/wootecobook/turkey/post/service/dto/PostRequest.java
  src/main/java/com/wootecobook/turkey/post/service/dto/PostResponse.java
  src/main/java/com/wootecobook/turkey/post/service/exception/NotFoundPostException.java
  src/main/java/com/wootecobook/turkey/post/service/exception/NotPostOwnerException.java
  src/main/resources/static/js/post/template.js
  src/test/java/com/wootecobook/turkey/post/controller/PostApiControllerTests.java
  src/test/java/com/wootecobook/turkey/post/domain/PostTest.java
  src/test/java/com/wootecobook/turkey/post/service/PostServiceTest.java
Labels: enhancement

#25 회원가입/로그인 프론트엔드
  src/main/resources/static/css/signup.css
  src/main/resources/static/images/logo/facebook-full-logo.png
  src/main/resources/static/images/logo/favicon.ico
  src/main/resources/static/images/logo/global.png
  src/main/resources/static/js/app.js
  src/main/resources/static/js/login/login.js
  src/main/resources/static/js/signup/signup.js
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/signup.html
Labels: enhancement

#27 [백엔드] 댓글 도메인 개발
  build.gradle
  src/main/java/com/wootecobook/turkey/comment/controller/CommentController.java
  src/main/java/com/wootecobook/turkey/comment/controller/api/CommentApiController.java
  src/main/java/com/wootecobook/turkey/comment/controller/api/CommentApiControllerAdvice.java
  src/main/java/com/wootecobook/turkey/comment/domain/Comment.java
  src/main/java/com/wootecobook/turkey/comment/domain/CommentAuthException.java
  src/main/java/com/wootecobook/turkey/comment/domain/CommentRepository.java
  src/main/java/com/wootecobook/turkey/comment/service/CommentService.java
  src/main/java/com/wootecobook/turkey/comment/service/dto/CommentCreate.java
  src/main/java/com/wootecobook/turkey/comment/service/dto/CommentResponse.java
  src/main/java/com/wootecobook/turkey/comment/service/dto/CommentUpdate.java
  src/main/java/com/wootecobook/turkey/comment/service/exception/CommentNotFoundException.java
  src/main/java/com/wootecobook/turkey/comment/service/exception/CommentSaveException.java
  src/main/java/com/wootecobook/turkey/commons/BaseEntity.java
  src/main/java/com/wootecobook/turkey/post/domain/Post.java
  src/test/java/com/wootecobook/turkey/comment/controller/api/CommentApiControllerTests.java
  src/test/java/com/wootecobook/turkey/comment/domain/CommentRepositoryTest.java
  src/test/java/com/wootecobook/turkey/comment/domain/CommentTest.java
  src/test/java/com/wootecobook/turkey/comment/service/CommentServiceTest.java
  src/test/java/com/wootecobook/turkey/user/controller/BaseControllerTests.java
Labels: enhancement

#29 [Fix] 댓글 push 안 한 부분 pr 후 머지
  src/main/java/com/wootecobook/turkey/comment/controller/api/CommentApiController.java
  src/main/java/com/wootecobook/turkey/comment/controller/api/CommentApiControllerAdvice.java
  src/main/java/com/wootecobook/turkey/comment/domain/Comment.java
  src/main/java/com/wootecobook/turkey/comment/domain/CommentAuthException.java
  src/main/java/com/wootecobook/turkey/comment/domain/CommentValidator.java
  src/main/java/com/wootecobook/turkey/comment/domain/exception/CommentUpdateFailException.java
  src/main/java/com/wootecobook/turkey/comment/domain/exception/InvalidCommentException.java
  src/main/java/com/wootecobook/turkey/comment/domain/exception/NotCommentOwnerException.java
  src/main/java/com/wootecobook/turkey/comment/service/CommentService.java
  src/main/java/com/wootecobook/turkey/comment/service/dto/CommentCreate.java
  src/main/java/com/wootecobook/turkey/comment/service/dto/CommentResponse.java
  src/main/java/com/wootecobook/turkey/comment/service/dto/CommentUpdate.java
  src/main/java/com/wootecobook/turkey/comment/service/exception/AlreadyDeleteException.java
  src/main/java/com/wootecobook/turkey/comment/service/exception/CommentNotFoundException.java
  src/main/java/com/wootecobook/turkey/comment/service/exception/CommentSaveException.java
  src/test/java/com/wootecobook/turkey/comment/controller/api/CommentApiControllerTests.java
  src/test/java/com/wootecobook/turkey/comment/domain/CommentTest.java
  src/test/java/com/wootecobook/turkey/comment/service/CommentServiceTest.java
Labels: bug

#30 배포 준비
  build.gradle
  deploy.sh
  gradlew
Labels: enhancement

#42 Post 프론트 피드백 반영
  src/main/java/com/wootecobook/turkey/commons/aop/LoggingAspect.java
  src/main/resources/static/js/post/post.js
Labels: refactor

#43 로그아웃 버튼 추가 및 프론트 피드백 반영
  src/main/resources/static/css/index.css
  src/main/resources/static/js/app.js
  src/main/resources/static/js/login/login.js
  src/main/resources/static/js/login/logout.js
  src/main/resources/static/js/signup/signup.js
  src/main/resources/templates/fragments/nav.html
  src/main/resources/templates/index.html
  src/main/resources/templates/signup.html
Labels: enhancement

#46 개인 피드 페이지
  .gitignore
  package-lock.json
  package.json
  src/main/resources/static/css/index.css
  src/main/resources/static/css/mypage.css
  src/main/resources/static/css/shared.css
  src/main/resources/static/js/mypage/mypage.js
  src/main/resources/static/js/mypage/template.js
  src/main/resources/static/js/post/template.js
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layouts/main.html
  src/main/resources/templates/mypage.html
Labels: enhancement

#47 댓글 프론트
  src/main/java/com/wootecobook/turkey/comment/domain/Comment.java
  src/main/java/com/wootecobook/turkey/comment/domain/CommentRepository.java
  src/main/java/com/wootecobook/turkey/comment/service/CommentService.java
  src/main/java/com/wootecobook/turkey/comment/service/dto/CommentResponse.java
  src/main/resources/static/css/app.css
  src/main/resources/static/js/comment/template.js
  src/main/resources/static/js/post/post.js
  src/main/resources/static/js/post/template.js
  src/main/resources/templates/index.html
  src/test/java/com/wootecobook/turkey/comment/domain/CommentRepositoryTest.java
  src/test/java/com/wootecobook/turkey/comment/service/CommentServiceTest.java
Labels: enhancement

#50 이름으로 검색
  src/main/java/com/wootecobook/turkey/user/controller/api/UserApiController.java
  src/main/java/com/wootecobook/turkey/user/domain/UserRepository.java
  src/main/java/com/wootecobook/turkey/user/service/UserService.java
  src/main/resources/data.sql
  src/main/resources/static/js/search/search.js
  src/main/resources/static/js/search/template.js
  src/main/resources/templates/fragments/nav.html
  src/main/resources/templates/index.html
  src/test/java/com/wootecobook/turkey/user/controller/api/UserApiControllerTests.java
  src/test/java/com/wootecobook/turkey/user/domain/UserRepositoryTest.java
Labels: enhancement

#51 fix: 댓글 수정폼 클릭시 답글도 수정폼 나오는 문제 해결
  src/main/resources/static/js/comment/template.js
  src/main/resources/static/js/post/post.js
Labels: bug

#52 fix: 댓글 개행 문제 해결
  src/main/resources/static/js/comment/template.js
  src/main/resources/static/js/mypage/mypage.js
  src/main/resources/static/js/post/post.js
Labels: bug

#54 [프론트] 댓글 시간 표시
  src/main/resources/data.sql
  src/main/resources/static/js/comment/template.js
Labels: enhancement

#55 친구 맺기
  src/main/java/com/wootecobook/turkey/friend/controller/api/FriendApiController.java
  src/main/java/com/wootecobook/turkey/friend/controller/api/FriendApiControllerAdvice.java
  src/main/java/com/wootecobook/turkey/friend/domain/Friend.java
  src/main/java/com/wootecobook/turkey/friend/domain/FriendAsk.java
  src/main/java/com/wootecobook/turkey/friend/domain/FriendAskRepository.java
  src/main/java/com/wootecobook/turkey/friend/domain/FriendRepository.java
  src/main/java/com/wootecobook/turkey/friend/service/FriendAskService.java
  src/main/java/com/wootecobook/turkey/friend/service/FriendService.java
  src/main/java/com/wootecobook/turkey/friend/service/dto/FriendAskCreate.java
  src/main/java/com/wootecobook/turkey/friend/service/dto/FriendAskResponse.java
  src/main/java/com/wootecobook/turkey/friend/service/dto/FriendCreate.java
  src/main/java/com/wootecobook/turkey/friend/service/dto/FriendResponse.java
  src/main/java/com/wootecobook/turkey/friend/service/exception/FriendAskFailException.java
  src/main/java/com/wootecobook/turkey/user/controller/api/UserApiController.java
  src/main/java/com/wootecobook/turkey/user/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/static/css/friendbar.css
  src/main/resources/static/css/index.css
  src/main/resources/static/images/default/icons3.png
  src/main/resources/static/js/friendask/load.js
  src/main/resources/static/js/friendask/template.js
  src/main/resources/static/js/friendbar/load.js
  src/main/resources/static/js/friendbar/template.js
  src/main/resources/templates/fragments/nav.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layouts/main.html
  src/test/java/com/wootecobook/turkey/friend/controller/api/FriendApiControllerTests.java
  src/test/java/com/wootecobook/turkey/friend/domain/FriendAskTest.java
  src/test/java/com/wootecobook/turkey/friend/service/FriendAskServiceTest.java
  src/test/java/com/wootecobook/turkey/friend/service/FriendServiceTest.java
  src/test/java/com/wootecobook/turkey/user/service/UserServiceTest.java
Labels: enhancement

#56 게시글 파일 첨부 기능 백엔드
  build.gradle
  src/main/java/com/wootecobook/turkey/config/AwsConfig.java
  src/main/java/com/wootecobook/turkey/file/domain/FileFeature.java
  src/main/java/com/wootecobook/turkey/file/domain/UploadFile.java
  src/main/java/com/wootecobook/turkey/file/domain/UploadFileRepository.java
  src/main/java/com/wootecobook/turkey/file/service/FailedSaveFileException.java
  src/main/java/com/wootecobook/turkey/file/service/FileDto.java
  src/main/java/com/wootecobook/turkey/file/service/UploadFileService.java
  src/main/java/com/wootecobook/turkey/post/controller/api/PostApiController.java
  src/main/java/com/wootecobook/turkey/post/domain/Post.java
  src/main/java/com/wootecobook/turkey/post/service/PostService.java
  src/main/java/com/wootecobook/turkey/post/service/dto/PostRequest.java
  src/main/java/com/wootecobook/turkey/post/service/dto/PostResponse.java
  src/main/java/com/wootecobook/turkey/utils/S3Connector.java
  src/main/resources/application.yml
  src/test/java/com/wootecobook/turkey/comment/controller/api/CommentApiControllerTests.java
  src/test/java/com/wootecobook/turkey/config/AwsMockConfig.java
  src/test/java/com/wootecobook/turkey/file/service/UploadFileServiceTest.java
  src/test/java/com/wootecobook/turkey/post/controller/PostApiControllerTests.java
  src/test/java/com/wootecobook/turkey/post/service/PostServiceTest.java
  src/test/java/com/wootecobook/turkey/utils/S3ConnectorTest.java
Labels: enhancement

#58 글 / 댓글 좋아요 백엔드
  src/main/java/com/wootecobook/turkey/comment/controller/api/CommentApiController.java
  src/main/java/com/wootecobook/turkey/comment/domain/CommentGood.java
  src/main/java/com/wootecobook/turkey/comment/domain/CommentGoodRepository.java
  src/main/java/com/wootecobook/turkey/comment/service/CommentGoodService.java
  src/main/java/com/wootecobook/turkey/comment/service/CommentService.java
  src/main/java/com/wootecobook/turkey/commons/Good.java
  src/main/java/com/wootecobook/turkey/commons/GoodResponse.java
  src/main/java/com/wootecobook/turkey/post/controller/api/PostApiController.java
  src/main/java/com/wootecobook/turkey/post/domain/PostGood.java
  src/main/java/com/wootecobook/turkey/post/domain/PostGoodRepository.java
  src/main/java/com/wootecobook/turkey/post/service/PostGoodService.java
  src/main/java/com/wootecobook/turkey/post/service/PostService.java
  src/main/resources/static/css/friendbar.css
  src/main/resources/static/css/mypage.css
  src/main/resources/static/images/default/chelsea.jpg
  src/main/resources/static/js/friendask/load.js
  src/main/resources/static/js/friendask/template.js
  src/main/resources/static/js/friendbar/load.js
  src/main/resources/static/js/friendbar/template.js
  src/main/resources/static/js/mypage/mypage.js
  src/main/resources/static/js/mypage/template.js
  src/main/resources/static/js/post/post.js
  src/main/resources/templates/fragments/nav.html
  src/main/resources/templates/layouts/main.html
  src/test/java/com/wootecobook/turkey/comment/controller/api/CommentApiControllerTests.java
  src/test/java/com/wootecobook/turkey/comment/domain/CommentGoodRepositoryTest.java
  src/test/java/com/wootecobook/turkey/comment/service/CommentServiceTest.java
  src/test/java/com/wootecobook/turkey/friend/controller/api/FriendApiControllerTests.java
  src/test/java/com/wootecobook/turkey/friend/service/FriendServiceTest.java
  src/test/java/com/wootecobook/turkey/post/controller/PostApiControllerTests.java
  src/test/java/com/wootecobook/turkey/post/domain/PostGoodRepositoryTest.java
  src/test/java/com/wootecobook/turkey/post/service/PostServiceTest.java
  src/test/java/com/wootecobook/turkey/user/service/UserServiceTest.java
Labels: enhancement

#60 게시글 첨부파일 리팩터링 적용
  src/main/java/com/wootecobook/turkey/config/AwsConfig.java
  src/main/java/com/wootecobook/turkey/file/domain/FileFeature.java
  src/main/java/com/wootecobook/turkey/file/domain/UploadFile.java
  src/main/java/com/wootecobook/turkey/file/service/FailedSaveFileException.java
  src/main/java/com/wootecobook/turkey/file/service/FileResponse.java
  src/main/java/com/wootecobook/turkey/file/service/UploadFileService.java
  src/main/java/com/wootecobook/turkey/post/controller/api/PostApiController.java
  src/main/java/com/wootecobook/turkey/post/domain/Contents.java
  src/main/java/com/wootecobook/turkey/post/domain/Post.java
  src/main/java/com/wootecobook/turkey/post/service/dto/PostRequest.java
  src/main/java/com/wootecobook/turkey/post/service/dto/PostResponse.java
  src/main/java/com/wootecobook/turkey/utils/S3Connector.java
  src/test/java/com/wootecobook/turkey/post/service/PostServiceTest.java
  src/test/java/com/wootecobook/turkey/utils/S3ConnectorTest.java
Labels: enhancement

#66 게시글 수정, 삭제 안되는 문제 및 댓글 에러 처리
  src/main/resources/static/js/post/post.js
  src/test/java/com/wootecobook/turkey/post/service/PostServiceTest.java
Labels: bug

#67 검색 결과 구현
  src/main/java/com/wootecobook/turkey/search/controller/web/SearchController.java
  src/main/java/com/wootecobook/turkey/user/controller/api/UserApiController.java
  src/main/java/com/wootecobook/turkey/user/domain/UserRepository.java
  src/main/java/com/wootecobook/turkey/user/service/UserDeleteService.java
  src/main/java/com/wootecobook/turkey/user/service/UserService.java
  src/main/resources/static/css/app.css
  src/main/resources/static/css/index.css
  src/main/resources/static/js/search/search.js
  src/main/resources/static/js/search/searchResult.js
  src/main/resources/static/js/search/searchbox.js
  src/main/resources/static/js/search/template.js
  src/main/resources/templates/fragments/nav.html
  src/main/resources/templates/index.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/search-result.html
  src/test/java/com/wootecobook/turkey/search/controller/web/SearchControllerTests.java
  src/test/java/com/wootecobook/turkey/user/controller/api/UserApiControllerTests.java
  src/test/java/com/wootecobook/turkey/user/domain/UserRepositoryTest.java
Labels: enhancement

#76 로컬스토리지 활용해서 프론트에서 로그인 유저정보 사용하기
  src/main/java/com/wootecobook/turkey/login/controller/LoginApiController.java
  src/main/resources/static/js/comment/template.js
  src/main/resources/static/js/login/login.js
  src/main/resources/static/js/login/logout.js
  src/main/resources/static/js/nav/setup.js
  src/main/resources/static/js/post/post.js
  src/main/resources/static/js/post/template.js
  src/main/resources/templates/fragments/nav.html
  src/main/resources/templates/index.html
  src/main/resources/templates/signup.html
  src/test/java/com/wootecobook/turkey/login/controller/LoginApiControllerTests.java
Labels: enhancement

#79 게시글 동영상 업로드 구현
  src/main/resources/application.yml
  src/main/resources/static/css/index.css
  src/main/resources/static/js/post/post.js
  src/main/resources/static/js/post/preview.js
  src/main/resources/static/js/post/template-carousel.js
  src/main/resources/static/js/post/template-file.js
  src/main/resources/static/js/post/template.js
  src/main/resources/templates/fragments/write-post.html
  src/main/resources/templates/index.html
  src/main/resources/templates/mypage.html
Labels: enhancement

#81 특정유저에게 글쓰기 구현
  src/main/java/com/wootecobook/turkey/commons/aop/LoggingAspect.java
  src/main/java/com/wootecobook/turkey/post/controller/PostApiControllerAdvice.java
  src/main/java/com/wootecobook/turkey/post/domain/Post.java
  src/main/java/com/wootecobook/turkey/post/service/PostService.java
  src/main/java/com/wootecobook/turkey/post/service/dto/PostRequest.java
  src/main/java/com/wootecobook/turkey/post/service/dto/PostResponse.java
  src/main/resources/data.sql
  src/main/resources/static/js/good/good.js
  src/main/resources/static/js/mypage/mypage.js
  src/main/resources/static/js/mypage/template-writeform.js
  src/main/resources/static/js/mypage/template.js
  src/main/resources/static/js/post/post.js
  src/main/resources/static/js/post/template.js
  src/main/resources/templates/mypage.html
  src/test/java/com/wootecobook/turkey/post/controller/PostApiControllerTests.java
Labels: enhancement

#84 코드리뷰에서 받은 Good 관련 피드백 반영했습니다.
  src/main/java/com/wootecobook/turkey/comment/controller/CommentApiController.java
  src/main/java/com/wootecobook/turkey/comment/service/CommentService.java
  src/main/java/com/wootecobook/turkey/commons/GoodResponse.java
  src/main/java/com/wootecobook/turkey/commons/GoodService.java
  src/main/java/com/wootecobook/turkey/file/service/UploadFileService.java
  src/main/java/com/wootecobook/turkey/good/domain/Good.java
  src/main/java/com/wootecobook/turkey/good/domain/comment/CommentGood.java
  src/main/java/com/wootecobook/turkey/good/domain/comment/CommentGoodRepository.java
  src/main/java/com/wootecobook/turkey/good/domain/post/PostGood.java
  src/main/java/com/wootecobook/turkey/good/domain/post/PostGoodRepository.java
  src/main/java/com/wootecobook/turkey/good/service/CommentGoodService.java
  src/main/java/com/wootecobook/turkey/good/service/GoodService.java
  src/main/java/com/wootecobook/turkey/good/service/PostGoodService.java
  src/main/java/com/wootecobook/turkey/good/service/dto/GoodResponse.java
  src/main/java/com/wootecobook/turkey/post/controller/PostApiController.java
  src/main/java/com/wootecobook/turkey/post/service/PostService.java
  src/main/java/com/wootecobook/turkey/post/service/dto/PostResponse.java
  src/main/resources/static/js/good/good.js
  src/test/java/com/wootecobook/turkey/comment/controller/CommentApiControllerTests.java
  src/test/java/com/wootecobook/turkey/comment/domain/CommentGoodRepositoryTest.java
  src/test/java/com/wootecobook/turkey/comment/service/CommentServiceTest.java
  src/test/java/com/wootecobook/turkey/post/controller/PostApiControllerTests.java
  src/test/java/com/wootecobook/turkey/post/domain/PostGoodRepositoryTest.java
  src/test/java/com/wootecobook/turkey/post/service/PostServiceTest.java
Labels: refactor

#85 [프론트] 댓글 좋아요
  src/main/java/com/wootecobook/turkey/comment/controller/CommentApiController.java
  src/main/java/com/wootecobook/turkey/comment/service/CommentService.java
  src/main/java/com/wootecobook/turkey/comment/service/dto/CommentResponse.java
  src/main/java/com/wootecobook/turkey/post/service/dto/PostResponse.java
  src/main/resources/static/css/app.css
  src/main/resources/static/css/index.css
  src/main/resources/static/js/comment/template.js
  src/main/resources/static/js/good/good.js
  src/main/resources/static/js/login/login.js
  src/main/resources/static/js/post/post.js
  src/main/resources/static/js/post/template.js
  src/test/java/com/wootecobook/turkey/comment/controller/CommentApiControllerTests.java
  src/test/java/com/wootecobook/turkey/comment/service/CommentServiceTest.java
Labels: enhancement

#90 개인 피드 페이지 소개 기능 추가
  src/main/java/com/wootecobook/turkey/user/controller/IntroductionApiController.java
  src/main/java/com/wootecobook/turkey/user/controller/UserApiController.java
  src/main/java/com/wootecobook/turkey/user/domain/Introduction.java
  src/main/java/com/wootecobook/turkey/user/domain/IntroductionRepository.java
  src/main/java/com/wootecobook/turkey/user/service/IntroductionService.java
  src/main/java/com/wootecobook/turkey/user/service/UserCreateService.java
  src/main/java/com/wootecobook/turkey/user/service/UserDeleteService.java
  src/main/java/com/wootecobook/turkey/user/service/UserService.java
  src/main/java/com/wootecobook/turkey/user/service/dto/IntroductionRequest.java
  src/main/java/com/wootecobook/turkey/user/service/dto/IntroductionResponse.java
  src/main/java/com/wootecobook/turkey/user/service/exception/UserMismatchException.java
  src/main/resources/data.sql
  src/main/resources/static/css/mypage.css
  src/main/resources/static/images/default/icons4.png
  src/main/resources/static/js/commons/app.js
  src/main/resources/static/js/leftpanel/leftpanel.js
  src/main/resources/static/js/login/login.js
  src/main/resources/static/js/mypage/mypage.js
  src/main/resources/static/js/mypage/template.js
  src/main/resources/static/js/post/post.js
  src/main/resources/static/js/signup/signup.js
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/fragments/left-panel.html
  src/main/resources/templates/index.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/signup.html
  src/test/java/com/wootecobook/turkey/friend/service/FriendAskServiceTest.java
  src/test/java/com/wootecobook/turkey/friend/service/FriendServiceTest.java
  src/test/java/com/wootecobook/turkey/post/service/PostServiceTest.java
  src/test/java/com/wootecobook/turkey/user/controller/IntroductionApiControllerTests.java
  src/test/java/com/wootecobook/turkey/user/service/IntroductionServiceTest.java
  src/test/java/com/wootecobook/turkey/user/service/UserCreateServiceTest.java
  src/test/java/com/wootecobook/turkey/user/service/UserDeleteServiceTest.java
  src/test/java/com/wootecobook/turkey/user/service/UserServiceTest.java
Labels: enhancement

#93 프로필 및 커버 사진업로드 구현
  src/main/java/com/wootecobook/turkey/commons/aws/S3Connector.java
  src/main/java/com/wootecobook/turkey/commons/converter/ImageTypeConverter.java
  src/main/java/com/wootecobook/turkey/config/WebConfig.java
  src/main/java/com/wootecobook/turkey/file/domain/UploadFileRepository.java
  src/main/java/com/wootecobook/turkey/file/service/UploadFileService.java
  src/main/java/com/wootecobook/turkey/user/controller/UserApiController.java
  src/main/java/com/wootecobook/turkey/user/domain/IntroductionRepository.java
  src/main/java/com/wootecobook/turkey/user/domain/User.java
  src/main/java/com/wootecobook/turkey/user/domain/UserRepository.java
  src/main/java/com/wootecobook/turkey/user/service/ImageType.java
  src/main/java/com/wootecobook/turkey/user/service/ImageUploader.java
  src/main/java/com/wootecobook/turkey/user/service/IntroductionService.java
  src/main/java/com/wootecobook/turkey/user/service/MyPageService.java
  src/main/java/com/wootecobook/turkey/user/service/UserCreateService.java
  src/main/java/com/wootecobook/turkey/user/service/UserImageUploadService.java
  src/main/java/com/wootecobook/turkey/user/service/UserService.java
  src/main/java/com/wootecobook/turkey/user/service/dto/MyPageResponse.java
  src/main/java/com/wootecobook/turkey/user/service/dto/UploadImage.java
  src/main/java/com/wootecobook/turkey/user/service/dto/UserResponse.java
  src/main/resources/static/css/mypage.css
  src/main/resources/static/js/comment/template.js
  src/main/resources/static/js/commons/api.js
  src/main/resources/static/js/mypage/mypage.js
  src/main/resources/static/js/mypage/profile-upload.js
  src/main/resources/static/js/mypage/template.js
  src/main/resources/templates/mypage.html
  src/test/java/com/wootecobook/turkey/friend/service/FriendAskServiceTest.java
  src/test/java/com/wootecobook/turkey/friend/service/FriendServiceTest.java
  src/test/java/com/wootecobook/turkey/search/controller/SearchControllerTests.java
  src/test/java/com/wootecobook/turkey/user/controller/IntroductionApiControllerTests.java
  src/test/java/com/wootecobook/turkey/user/controller/UserApiControllerTests.java
  src/test/java/com/wootecobook/turkey/user/domain/UserRepositoryTest.java
  src/test/java/com/wootecobook/turkey/user/service/IntroductionServiceTest.java
  src/test/java/com/wootecobook/turkey/user/service/MyPageServiceTest.java
  src/test/java/com/wootecobook/turkey/user/service/UserCreateServiceTest.java
  src/test/java/com/wootecobook/turkey/user/service/UserDeleteServiceTest.java
  src/test/java/com/wootecobook/turkey/user/service/UserImageUploadServiceTest.java
  src/test/java/com/wootecobook/turkey/user/service/UserServiceTest.java
Labels: enhancement

#95 현재 접속중인 친구 확인하기
  src/main/java/com/wootecobook/turkey/TurkeyApplication.java
  src/main/java/com/wootecobook/turkey/comment/domain/Comment.java
  src/main/java/com/wootecobook/turkey/commons/listener/UserSessionListener.java
  src/main/java/com/wootecobook/turkey/commons/resolver/UserSession.java
  src/main/java/com/wootecobook/turkey/friend/service/dto/FriendResponse.java
  src/main/java/com/wootecobook/turkey/good/domain/Good.java
  src/main/java/com/wootecobook/turkey/good/domain/comment/CommentGood.java
  src/main/java/com/wootecobook/turkey/good/domain/post/PostGood.java
  src/main/java/com/wootecobook/turkey/login/controller/LoginApiController.java
  src/main/java/com/wootecobook/turkey/login/service/LoginService.java
  src/main/java/com/wootecobook/turkey/post/domain/Post.java
  src/main/java/com/wootecobook/turkey/user/domain/User.java
  src/main/java/com/wootecobook/turkey/user/service/dto/UserResponse.java
  src/main/resources/application.yml
  src/main/resources/static/js/friendbar/template.js
  src/main/resources/static/js/mypage/mypage.js
  src/test/java/com/wootecobook/turkey/commons/listener/UserSessionListenerTest.java
  src/test/java/com/wootecobook/turkey/login/service/LoginServiceTest.java
  src/test/java/com/wootecobook/turkey/post/service/PostServiceTest.java
  src/test/java/com/wootecobook/turkey/user/controller/IntroductionApiControllerTests.java
  src/test/java/com/wootecobook/turkey/user/domain/UserTest.java
Labels: enhancement

#99 유저 정보 표시할 때 프로필 사진도 표시되도록 구현
  src/main/java/com/wootecobook/turkey/login/controller/LoginApiController.java
  src/main/resources/static/js/comment/template.js
  src/main/resources/static/js/friendbar/template.js
  src/main/resources/static/js/leftpanel/leftpanel.js
  src/main/resources/static/js/login/login.js
  src/main/resources/static/js/login/logout.js
  src/main/resources/static/js/mypage/profile-upload.js
  src/main/resources/static/js/nav/setup.js
  src/main/resources/static/js/post/template.js
  src/main/resources/templates/fragments/left-panel.html
  src/main/resources/templates/fragments/nav.html
Labels: enhancement

#116 댓글 업데이트 안되는 문제 해결
  src/main/resources/static/js/post/post.js
Labels: bug

#117 이메일 중복 가입시 메시지 수정
  src/main/java/com/wootecobook/turkey/user/service/UserService.java
  src/test/java/com/wootecobook/turkey/user/controller/UserApiControllerTests.java
  src/test/java/com/wootecobook/turkey/user/service/UserServiceTest.java
Labels: bug

#119 비밀번호 정규식 수정
  src/main/java/com/wootecobook/turkey/user/domain/UserValidator.java
  src/test/java/com/wootecobook/turkey/user/controller/UserApiControllerTests.java
  src/test/java/com/wootecobook/turkey/user/domain/UserTest.java
Labels: bug
